### ISSUE TITLE
member plugin - breaks members?

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/uchaguzi#65] opened 2013-02-18 16:01 UTC
Attempted to upgrade Jep to super admin.

Received error: Database error: Unknown column 'user_id' in 'where clause' - SELECT `id`, `adminsection_title` FROM `adminsection` WHERE `user_id` = '13' ORDER BY `adminsection`.`id` ASC 

clicked save:

Runtime Message

An error was detected which prevented the loading of this page. If this problem persists, please contact the website administrator.

plugins/election/hooks/election.php [174]:

Undefined index: adminsection_title

Report This Issue To Ushahidi

Loaded in 0.2523 seconds, using 7.80MB of memory. Generated by Ushahidi v2.5.

**Comment by aoduor** [comment] 2013-02-18 16:02
Duplicate of #63.

**Closed as completed** 2013-02-18 18:36 UTC
Labels: bug
