### ISSUE TITLE
CSS missing from /members/dashboard

### ISSUE THREAD

**Issue by jetherton** [ushahidi/uchaguzi#60] opened 2013-02-15 22:39 UTC
Take a look at this screen shot. Chromium/Ubuntu 12.04
![Uchaguzi dash](https://f.cloud.github.com/assets/275566/162565/6af43fae-77c0-11e2-8588-10b1264882b0.png)

**Comment by rjmackay** [comment] 2013-02-15 23:35
Related to/duplicate of #36 and #46 ?

**Comment by aoduor** [comment] 2013-02-18 06:32
Closing, as is a duplicate of #36

**Closed as completed by aoduor** 2013-02-18 06:32 UTC
