### ISSUE TITLE
Member UI - skewed

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/uchaguzi#57] opened 2013-02-13 19:06 UTC
When a member or superadmin logs into the dashboard, their view is skewed. I was advised that a ticket or action was assigned. Adding as it is not in github

screenshot http://cl.ly/image/4133172Q1u2Y

**Comment by rjmackay** [comment] 2013-02-13 20:36
Probably related or duplicate of #36

**Comment by kamaulynder** [comment] 2013-02-13 22:18
Yes, working on it also.

**Comment by aoduor** [comment] 2013-02-18 06:32
Closing, as is a duplicate of #36

**Closed as completed by aoduor** 2013-02-18 06:32 UTC
Labels: bug
