### ISSUE TITLE
Clean URLs option inconsistent with options selected

### ISSUE THREAD

**Issue by aoduor** [ushahidi/uchaguzi#7] opened 2013-01-14 13:33 UTC
Despite the fact that this is automatically set to NO, sometimes, my URLs are clean, sometimes they're not.
e.g for homepage - [my_url]/index.php/main
Addons page - [my_url]/admin/addons/plugins/

**Comment by kamaulynder** [comment] 2013-02-04 21:07
Closing this as I can't reproduce on my local or the live site http://simulation.uchaguzi.co.ke/

**Closed as completed by kamaulynder** 2013-02-04 21:07 UTC
Labels: bug
